# WEB APPLICATIONS VULNERBILITY SCANNER

COMPANY : CODTECH IT SOLUTIONS

NAME: KUNUKU SUSHMA

INTERN ID : CTO6DN1234

DOMAIN : CYBER SECURITY AND ETHICAL HACKING

DURATION : 6 WEEKS

MENTOR : NEELA SANTHOSH

output

![Task 2 output](https://github.com/user-attachments/assets/c9425b4a-f1f5-4fd9-a427-b3563a5413f6)



